development:
 adapter: sqlite3
 encoding: utf8
 database: my_app_development
 pool: 5
 username: root
 password:

test:
 adapter: sqlite3
 encoding: utf8
 database: my_app_test
 pool: 5
 username: root
 password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
